-- Rollback for schemas creation
DROP SCHEMA IF EXISTS notificaciones CASCADE;
DROP SCHEMA IF EXISTS facturacion CASCADE;
DROP SCHEMA IF EXISTS abordaje CASCADE;
DROP SCHEMA IF EXISTS ventas CASCADE;
DROP SCHEMA IF EXISTS operaciones CASCADE;
DROP SCHEMA IF EXISTS aeronaves CASCADE;
DROP SCHEMA IF EXISTS aeropuerto CASCADE;
DROP SCHEMA IF EXISTS clientes CASCADE;
DROP SCHEMA IF EXISTS seguridad CASCADE;
DROP SCHEMA IF EXISTS identidad CASCADE;
DROP SCHEMA IF EXISTS aerolinea CASCADE;
DROP SCHEMA IF EXISTS geografia CASCADE;
